services:
  umbrel:
    image: dockurr/umbrel
    container_name: umbrel
    restart: unless-stopped
    pid: host
    ports:
      - 80:80
    volumes:
      - "/Volumes/ADATA/umbrel/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    stop_grace_period: 3m
